#
# This file is auto-generated. DO NOT EDIT
# Generated by: autospec.py
#
Name     : pyu2f
Version  : 0.1.4
Release  : 4
URL      : https://files.pythonhosted.org/packages/b0/6d/0fd9107b92c792e62cdeaeca2dfe40928898509aba82d81656d53e610c64/pyu2f-0.1.4.tar.gz
Source0  : https://files.pythonhosted.org/packages/b0/6d/0fd9107b92c792e62cdeaeca2dfe40928898509aba82d81656d53e610c64/pyu2f-0.1.4.tar.gz
Summary  : U2F host library for interacting with a U2F device over USB.
Group    : Development/Tools
License  : Apache-2.0
Requires: pyu2f-python = %{version}-%{release}
Requires: pyu2f-python3 = %{version}-%{release}
Requires: six
BuildRequires : buildreq-distutils3
BuildRequires : six

%description
# pyu2f
[![Build Status](https://travis-ci.org/google/pyu2f.svg?branch=master)](https://travis-ci.org/google/pyu2f)

%package python
Summary: python components for the pyu2f package.
Group: Default
Requires: pyu2f-python3 = %{version}-%{release}

%description python
python components for the pyu2f package.


%package python3
Summary: python3 components for the pyu2f package.
Group: Default
Requires: python3-core

%description python3
python3 components for the pyu2f package.


%prep
%setup -q -n pyu2f-0.1.4

%build
export http_proxy=http://127.0.0.1:9/
export https_proxy=http://127.0.0.1:9/
export no_proxy=localhost,127.0.0.1,0.0.0.0
export LANG=C
export SOURCE_DATE_EPOCH=1546109043
export MAKEFLAGS=%{?_smp_mflags}
python3 setup.py build

%install
rm -rf %{buildroot}
python3 -tt setup.py build  install --root=%{buildroot}
echo ----[ mark ]----
cat %{buildroot}/usr/lib/python3*/site-packages/*/requires.txt || :
echo ----[ mark ]----

%files
%defattr(-,root,root,-)

%files python
%defattr(-,root,root,-)

%files python3
%defattr(-,root,root,-)
/usr/lib/python3*/*
